{
 "title": "Elasticsearch - Logs from Fluentd",
 "description": "Some basic statistics and message distribution across pods and namespaces",
 "tags": [
  "Elasticsearch",
  "Kibana",
  "Logs"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Filter" },
   {
    "name": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "content": "<img src=https://static-www.elastic.co/assets/blt9a26f88bfbd20eb5/icon-elasticsearch-bb.svg?q=540 height=80>  <h1><br>Elasticsearch</h1>"
  },
  {
   "title": "Total Documents",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indexes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "_index",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Error types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Error types",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "\"Error\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*error*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Fatal\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*fatal*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Exception\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*exception*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Fail\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*fail*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Warning\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*warning*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Could not\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*could not*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Info\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*info*",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Cron\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*cron*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Stream",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "\"Std error\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "stream:\"stderr\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "\"Std output\"",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "stream:\"stdout\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Pod / Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Logs per host - Fluentd",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.host.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs per namespace - Top 10",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "$Interval",
        "min_doc_count": 0,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "4", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs per namespace - Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "kubernetes.host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pods writing logs - Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}