{
 "title": "Logs",
 "description": "Dashboard for service logs inspection, received via Fluent-bit & Loki",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "stack_name", "label": "Stack", "query": "label_values(stack_name)" },
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values({stack_name =~ \"$stack_name\"}, service_name)"
   },
   {
    "name": "task_slot",
    "label": "Task",
    "query": "label_values({stack_name =~ \"$stack_name\", service_name =~ \"$service_name\"}, slot)"
   },
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values({stack_name =~ \"$stack_name\", service_name =~ \"$service_name\", slot =~ \"$task_slot\"}, container_name)"
   },
   { "name": "searchable_pattern", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log lines",
   "type": "stat",
   "description": "Total count of log lines in the specified time range",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Log lines with '$searchable_pattern'",
   "type": "stat",
   "description": "Total count of log lines containing '$searchable_pattern' in the specified time range",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched '$searchable_pattern' ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ \"(?i)$searchable_pattern\" | json | line_format \"{{.log}}\" | label_format log=\"\"",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "Log level count",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(alert)|(crit)|(critical)|(fatal)|(emerg)`)[$__interval]))",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(error)|(eror)|(err)`)[$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(warn)|(warning)`)[$__interval]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(info)|(information)|(informational)|(notice)`)[$__interval]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(debug)|(dbug)`)[$__interval]))",
     "legendFormat": "Debug"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)trace`)[$__interval]))",
     "legendFormat": "Trace"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} !~ `(?i)(alert)|(crit)|(critical)|(fatal)|(emerg)|(error)|(eror)|(err)|(warn)|(warning)|(info)|(information)|(informational)|(notice)|(debug)|(dbug)|(trace)`)[$__interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Matched '$searchable_pattern' count by service",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Log level count over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(alert)|(crit)|(critical)|(fatal)|(emerg)`)[$__interval]))",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(error)|(eror)|(err)`)[$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(warn)|(warning)`)[$__interval]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(info)|(information)|(informational)|(notice)`)[$__interval]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)(debug)|(dbug)`)[$__interval]))",
     "legendFormat": "Debug"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ `(?i)trace`)[$__interval]))",
     "legendFormat": "Trace"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} !~ `(?i)(alert)|(crit)|(critical)|(fatal)|(emerg)|(error)|(eror)|(err)|(warn)|(warning)|(info)|(information)|(informational)|(notice)|(debug)|(dbug)|(trace)`)[$__interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Matched '$searchable_pattern' count by service over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}