apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}

  - name: Loki
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}

  - name: PostgreSQL
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}
    url: ${PROMETHEUS_URL}
    isDefault: true
    version: 1
    editable: true

  - name: Loki
    type: loki
    access: proxy
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}
    url: ${LOKI_URL}
    isDefault: false
    version: 1
    editable: true

  - name: PostgreSQL
    type: postgres
    orgId: ${GF_USERS_AUTO_ASSIGN_ORG_ID}
    url: ${POSTGRES_URL}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASS}
    jsonData:
      sslmode: "disable"
      maxOpenConns: 3
      maxIdleConns: 1
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
    version: 1
    editable: true
