volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${DATA_VOL_DEVICE:-/grafana-vol/}

  dashboards-vol:
    name: ${DASHBOARDS_VOL_NAME}
    driver: ${DEV_VOL_DRIVER}
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},vers=${VOL_VERS},${VOL_OPTS}
      device: :${VOL_DEVICE_PREFIX}${DASHBOARDS_VOL_DEVICE:-/grafana-dashboards-vol/}
