version: '3.9'

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  dashboards-vol:
    name: ${DASHBOARDS_VOL_NAME}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared
