version: '3.9'

services:
  grafana:
    image: ${IMAGE_NAME:-grafana/grafana}:${IMAGE_TAG:-latest}
    environment:
      GF_SERVER_ROOT_URL: ${TRAEFIK_PROTOCOL}://${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      GF_PATHS_DATA:
      GF_PATHS_PROVISIONING:
      GF_INSTALL_PLUGINS:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS:
      GF_SERVER_HTTP_PORT:
      GF_SERVER_ENABLE_GZIP:
      GF_SECURITY_ADMIN_USER:
      GF_SECURITY_ADMIN_PASSWORD:
      GF_SECURITY_ALLOW_EMBEDDING:
      GF_USERS_ALLOW_SIGN_UP:
      GF_USERS_AUTO_ASSIGN_ORG:
      GF_USERS_AUTO_ASSIGN_ORG_ID:
      GF_USERS_AUTO_ASSIGN_ORG_ROLE:
      GF_SMTP_ENABLED:
      GF_SMTP_FROM_ADDRESS:
      GF_SMTP_FROM_NAME:
      GF_SMTP_HOST:
      GF_SMTP_SKIP_VERIFY:
      GF_SMTP_USER:
      GF_SMTP_PASSWORD:
      GF_LOG_MODE:
      GF_LOG_LEVEL:
      GF_AUTH_ANONYMOUS_ENABLED:
      GF_FEATURE_TOGGLES_ENABLE:
      DASHBOARDS_PATH:
      PROMETHEUS_URL:
      LOKI_URL:
      POSTGRES_URL:
      POSTGRES_USER:
      POSTGRES_PASS:
      POSTGRES_DB:
    networks:
      metric-net:
      traefik-net:
      log-net:
      postgres-net:
    volumes:
      - data-vol:${GF_PATHS_DATA}
    configs:
      - source: datasources-config
        target: ${GF_PATHS_PROVISIONING}/datasources/datasources.yml
      - source: dashboards-providers-config
        target: ${GF_PATHS_PROVISIONING}/dashboards/dashboards_providers.yml
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.grafana.entrypoints: ${TRAEFIK_ENTRYPOINT:-http}
        traefik.http.routers.grafana.rule: Host(`${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.services.grafana.loadbalancer.server.port: ${GF_SERVER_HTTP_PORT}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-512M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-128M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

  log-net:
    name: ${LOG_NET_NAME:-log-net}
    driver: ${LOG_NET_DRIVER:-overlay}
    external: true

  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    driver: ${POSTGRES_NET_DRIVER:-overlay}
    external: true

configs:
  datasources-config:
    name: ${DATASOURCES_CONFIG_NAME:-grafana-datasources}
    file: ./config/datasources.yml

  dashboards-providers-config:
    name: ${DASHBOARDS_PROVIDERS_CONFIG_NAME:-grafana-dashboards-providers}
    file: ./config/dashboards_providers.yml
