{
 "title": "Logs",
 "description": "Dashboard for service logs inspection, received via Fluent-bit & Loki",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "stack_name", "label": "Stack", "query": "label_values(stack_name)" },
   {
    "name": "service_name",
    "label": "Service",
    "query": "label_values({stack_name =~ \"$stack_name\"}, service_name)"
   },
   {
    "name": "task_slot",
    "label": "Task",
    "query": "label_values({stack_name =~ \"$stack_name\", service_name =~ \"$service_name\"}, slot)"
   },
   {
    "name": "container_name",
    "label": "Container",
    "query": "label_values({stack_name =~ \"$stack_name\", service_name =~ \"$service_name\", slot =~ \"$task_slot\"}, container_name)"
   },
   { "name": "level", "label": "Level", "query": "label_values(level)" },
   { "name": "searchable_pattern", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log lines count",
   "type": "stat",
   "description": "Total count of log lines in the specified time range",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Log lines with '$searchable_pattern' count",
   "type": "stat",
   "description": "Total count of log lines containing '$searchable_pattern' in the specified time range",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\"",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "Count by level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"critical\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"error\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"warning\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"info\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"debug\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Debug"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"trace\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Trace"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level!~\"critical|error|warning|info|debug|trace\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Matched '$searchable_pattern' count by service",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Count by level over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"critical\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"error\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"warning\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Warning"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"info\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"debug\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Debug"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\", level=\"trace\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Trace"
    },
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level!~\"critical|error|warning|info|debug|trace\"} |~ \"(?i)$searchable_pattern\")[$__interval]))",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Matched '$searchable_pattern' count by service over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({stack_name=~\"$stack_name\", service_name=~\"$service_name\", slot=~\"$task_slot\", container_name=~\"$container_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}